<a href="https://colab.research.google.com/github/Priyanshu27083/ML_lab/blob/main/scikit.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#23/07
import pandas as pd
sales = pd.DataFrame({2014:[100.5,150.8,200.9,30000,40000],2015:[12000,18000,22000,30000,45000],2016:[20000,50000,70000,100000,125000],2017:[50000,60000,70000,80000,90000]},index = ['A','B','C','D','E'])
print(sales)
print(sales.index)
print(sales.columns)
print(sales.describe())
print(sales.shape)
print(sales.size)
print(sales.head(2))
print(sales.iloc[:,:2])

      2014   2015    2016   2017
A    100.5  12000   20000  50000
B    150.8  18000   50000  60000
C    200.9  22000   70000  70000
D  30000.0  30000  100000  80000
E  40000.0  45000  125000  90000
Index(['A', 'B', 'C', 'D', 'E'], dtype='object')
Index([2014, 2015, 2016, 2017], dtype='int64')
               2014          2015         2016          2017
count      5.000000      5.000000       5.0000      5.000000
mean   14090.440000  25400.000000   73000.0000  70000.000000
std    19412.436122  12759.310326   41170.3777  15811.388301
min      100.500000  12000.000000   20000.0000  50000.000000
25%      150.800000  18000.000000   50000.0000  60000.000000
50%      200.900000  22000.000000   70000.0000  70000.000000
75%    30000.000000  30000.000000  100000.0000  80000.000000
max    40000.000000  45000.000000  125000.0000  90000.000000
(5, 4)
20
    2014   2015   2016   2017
A  100.5  12000  20000  50000
B  150.8  18000  50000  60000
      2014   2015
A    100.5  12000
B    150.8  18000
C    200.9  22000
D  30000.0  30000
E  40000.0  45000

In [ ]:
dict1 = {2018:[160000,110000,500000,340000,900000]}
sales2 = pd.DataFrame(dict1, index = ['A','B','C','D','E'])
print(sales2)
print(sales2.empty)

     2018
A  160000
B  110000
C  500000
D  340000
E  900000
False

In [ ]:
#Appending
appended = pd.concat([sales,sales2], axis = 1)
print(appended)

      2014   2015    2016   2017    2018
A    100.5  12000   20000  50000  160000
B    150.8  18000   50000  60000  110000
C    200.9  22000   70000  70000  500000
D  30000.0  30000  100000  80000  340000
E  40000.0  45000  125000  90000  900000

In [ ]:
appended.transpose()

             A         B         C         D         E
2014     100.5     150.8     200.9   30000.0   40000.0
2015   12000.0   18000.0   22000.0   30000.0   45000.0
2016   20000.0   50000.0   70000.0  100000.0  125000.0
2017   50000.0   60000.0   70000.0   80000.0   90000.0
2018  160000.0  110000.0  500000.0  340000.0  900000.0

In [ ]:
appended[2017]

A    50000
B    60000
C    70000
D    80000
E    90000
Name: 2017, dtype: int64